disabled_rules:
  - force_cast
  - identifier_name
  - todo
  - void_return
excluded:
  - Submodules/
  - RxAlamofire/
  - Pods/
  - vendor/bundle
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - override_in_extension
  - private_action
  - private_outlet
  - required_enum_case
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
file_length:
  warning: 800
  error: 1200
function_body_length:
  warning: 40
  error: 50
line_length:
  warning: 150
  error: 160
type_body_length:
  warning: 500
  error: 1000