# .circleci/config.yml
# Run commands are executed using non-login shells by default,
# so you must explicitly source any dotfiles as part of the command.
version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      FASTLANE_LANE: staging
    shell: /bin/bash --login -o pipefail
    steps:
      - run:
          name: Install Node Version Manager (v0.33.11)
          command: |
            cd ~/
            git clone https://github.com/creationix/nvm.git ~/.nvm
            cd ~/.nvm && git checkout v0.33.11 && source nvm.sh
            nvm install v7.9.0 && nvm use v7.9.0
      - checkout
      - run: git submodule update --init
      - run: sh scripts/install-js.sh && sh scripts/build-js.sh
      - run:
          name: Build OpenSSL
          command: sh Submodules/OpenSSL-for-iPhone/build-libssl.sh
      #- run:
          # If beta version is required:
          # name: Install CocoaPods
          # command: gem install cocoapods --pre
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE