# .circleci/config.yml
version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      FASTLANE_LANE: staging
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: cd ~/ && mkdir .nvm
      - run: git clone https://github.com/creationix/nvm.git .nvm
      - run: cd .nvm && git checkout v0.33.11
      - run: source .nvm/nvm.sh
      - run: cd ~
      - run: nvm install v7.9.0 && nvm use v7.9.0
      - run: git submodule update --init
      - run: sh scripts/install-js.sh && sh scripts/build-js.sh
      - run:
          name: Build OpenSSL
          command: sh Submodules/OpenSSL-for-iPhone/build-libssl.sh
      #- run:
          # If beta version is required:
          # name: Install CocoaPods
          # command: gem install cocoapods --pre
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE