#
#  .circleci/config.yml
#  Blockchain
#
#  Created by Maurice A. on 10/1/18.
#  Copyright © 2018 Blockchain Luxembourg S.A. All rights reserved.
#
# Run commands are executed using non-login shells by default,
# so you must explicitly source any dotfiles as part of the command.
# It’s possible to specify a multi-line command, each line of which will be run in the same shell.

version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      # Target iOS SDK version
      TARGET_IOS_SDK_VERSION: 12.0

      # Specifies which environment Fastlane should build against.
      FASTLANE_LANE: staging

      # Specifies the required node version (also used as part of the cache key).
      NODE_VERSION: v7.9.0

      # Changing this value invalidates the cache, causing the new version of node to be installed.
      NODE_CACHE_KEY: node-cache-{{ .Environment.NODE_VERSION }}

      # Cache key of the compiled OpenSSL library for the targeted SDK version.
      OPENSSL_CACHE_KEY: openssl-cache-{{ .Environment.TARGET_IOS_SDK_VERSION }}

    shell: /bin/bash --login -o pipefail

    steps:
      - restore_cache:
          keys:
            - ${NODE_CACHE_KEY}
            - ${OPENSSL_CACHE_KEY}
      - run:
          name: Install Node
          command: |
            cd ~
            git clone https://github.com/creationix/nvm.git .nvm
            cd .nvm && git checkout v0.33.11 && . nvm.sh
            nvm install $NODE_VERSION && nvm use $NODE_VERSION
            if [[ $(npm -v | grep -v "5.6.0") ]] ; then npm install -g npm@5.6.0; fi
      - save_cache:
          key: ${NODE_CACHE_KEY}
          paths:
            - ~/.nvm
            - /usr/local/lib/node_modules
      # - checkout
      # - run:
      #     name: Initialize submodules
      #     command: git submodule update --init
      # - run:
      #     name: Build JS
      #     command: . ~/.nvm/nvm.sh && sh scripts/install-js.sh && sh scripts/build-js.sh
      # - run:
      #     name: Build OpenSSL
      #     command: |
      #       cd Submodules/OpenSSL-for-iPhone
      #       sh build-libssl.sh --cleanup
      #- run:
          # If beta version is required:
          # name: Install CocoaPods
          # command: gem install cocoapods --pre
      # - run: bundle install
      # - run:
      #     name: Fastlane
      #     command: bundle exec fastlane $FASTLANE_LANE