#
#  .circleci/config.yml
#  Blockchain
#
#  Created by Maurice A. on 10/1/18.
#  Copyright © 2018 Blockchain Luxembourg S.A. All rights reserved.
#
# Run commands are executed using non-login shells by default,
# so you must explicitly source any dotfiles as part of the command.
# It’s possible to specify a multi-line command, each line of which will be run in the same shell.

version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      FASTLANE_LANE: staging
    shell: /bin/bash --login -o pipefail
    steps:
      - run:
          name: Install node version manager (v0.33.11)
          command: |
            cd ~/
            git clone https://github.com/creationix/nvm.git ~/.nvm
            cd ~/.nvm && git checkout v0.33.11 && source nvm.sh
            nvm install v7.9.0 && nvm use v7.9.0
            npm install -g npm@5.6.0
      - checkout
      - run:
          name: Initialize submodules
          command: git submodule update --init
      - run:
          name: Build JS
          command: source ~/.nvm/nvm.sh && sh scripts/install-js.sh && sh scripts/build-js.sh
      - run:
          name: Build OpenSSL
          command: |
            cd Submodules/OpenSSL-for-iPhone
            sh build-libssl.sh --cleanup
      #- run:
          # If beta version is required:
          # name: Install CocoaPods
          # command: gem install cocoapods --pre
      # - run: bundle install
      # - run:
      #     name: Fastlane
      #     command: bundle exec fastlane $FASTLANE_LANE